### ISSUE TITLE
Using OSQP-Eigen with OSQP CUDA

### ISSUE THREAD

**Issue by JTylerBoylan** [robotology/osqp-eigen#148] opened 2023-10-09 18:46 UTC
I got OSQP-Eigen to build and solve when I build OSQP with its normal linear algebra library, but when I build OSQP with it's CUDA library instead, I get a compilation error for OSQP-Eigen.

Compilation Error:
```
/usr/bin/ld: CMakeFiles/main.dir/src/main.cpp.o: in function `bool OsqpEigen::SparseMatrixHelper::createOsqpSparseMatrix<Eigen::SparseMatrix<float, 0, int> >(Eigen::SparseCompressedBase<Eigen::SparseMatrix<float, 0, int> > const&, OSQPCscMatrix*&)':
/usr/local/include/OsqpEigen/SparseMatrixHelper.tpp:42: undefined reference to `csc_spalloc'
/usr/bin/ld: /usr/local/lib/libOsqpEigen.so.0.8.1: undefined reference to `csc_spfree'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/main.dir/build.make:99: main] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/main.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

Dockerfile:
```
FROM nvidia/cuda:12.2.0-devel-ubuntu22.04

RUN apt-get update -y

RUN apt-get install -y cmake git

RUN apt-get install -y libeigen3-dev

RUN git clone https://github.com/osqp/osqp
RUN cd osqp && mkdir build
RUN cd osqp/build && cmake -G "Unix Makefiles" .. -DOSQP_ALGEBRA_BACKEND=cuda
# RUN cd osqp/build && cmake -G "Unix Makefiles" ..
# Does not fail when using above ^
RUN cd osqp/build && cmake --build . --target install

RUN git clone https://github.com/robotology/osqp-eigen
RUN cd osqp-eigen && mkdir build
RUN cd osqp-eigen/build && cmake ..
RUN cd osqp-eigen/build && make && make install
```

CMakeLists.txt:
```
cmake_minimum_required(VERSION 3.5)
project(my_project)

set(CMAKE_BUILD_TYPE RelWithDebInfo)

find_package(OsqpEigen REQUIRED)
find_package(Eigen3)

include_directories(SYSTEM ${EIGEN3_INCLUDE_DIR})

include_directories(include)

# Add the executable
add_executable(main src/main.cpp)
target_include_directories(main PUBLIC include)
target_link_libraries(main PUBLIC stdc++ stdc++fs m OsqpEigen::OsqpEigen)
```

**Comment by rohitashwin** [comment] 2024-11-11 00:32
Hey any updates on this issue?

**Comment by traversaro** [comment] 2024-11-11 06:18
Did you check if the problem is still there after https://github.com/robotology/osqp-eigen/pull/163 ?

**Comment by rohitashwin** [comment] 2024-11-11 23:44
Hey traversaro, thanks for the response. Yes the problem still persists, mainly, I'm facing this issue:

```
terminate called after throwing an instance of 'thrust::THRUST_200500_600_750_NS::system::system_error'
  what():  parallel_for failed: cudaErrorInvalidDevice: invalid device ordinal
```

It happens when solver->Run() is called.

**Comment by traversaro** [comment] 2024-11-12 06:03
> Hey traversaro, thanks for the response. Yes the problem still persists, mainly, I'm facing this issue:
> 
> ```
> terminate called after throwing an instance of 'thrust::THRUST_200500_600_750_NS::system::system_error'
>   what():  parallel_for failed: cudaErrorInvalidDevice: invalid device ordinal
> ```
> 
> It happens when solver->Run() is called.

That is a different error from the one in the original post. In the same environment in which you got this result, does osqp on its own work with CUDA backend?

**Comment by rohitashwin** [comment] 2024-11-12 07:33
```
2: -------------------------------------------------------------------------------
2: Unconstrained solve
2: -------------------------------------------------------------------------------
2: /root/osqp/tests/unconstrained/test_unconstrained.cpp:10
2: ...............................................................................
2: 
2: /root/osqp/tests/unconstrained/test_unconstrained.cpp:28: FAILED:
2: due to unexpected exception with messages:
2:   settings->linsys_solver := 2
2:   settings->polishing := 1
2:   parallel_for failed: cudaErrorInvalidDevice: invalid device ordinal
2: 
2: -------------------------------------------------------------------------------
2: Test updating P and A
2: -------------------------------------------------------------------------------
2: /root/osqp/tests/update_matrices/test_update_matrices.cpp:94
2: ...............................................................................
2: 
2: /root/osqp/tests/update_matrices/test_update_matrices.cpp:108: FAILED:
2: due to unexpected exception with messages:
2:   settings->linsys_solver := 2
2:   parallel_for failed: cudaErrorInvalidDevice: invalid device ordinal
2: 
2: ===============================================================================
2: test cases: 13 | 13 failed
2: assertions: 25 | 9 passed | 16 failed
2: 
2/2 Test #2: osqp_tester ......................***Failed    2.06 sec
```

Oh it looks like the issue arises in just osqp

**Comment by traversaro** [comment] 2024-11-12 07:57
Thanks! So I guess the issue is just in osqp or (that is my guess) there is something specific on your machine? As this problem was related to a compilation problem with osqp-eigen + osqp with CUDA backend enable, and that works fine, if it is ok for you I would close the issue. Feel free to open a new issue for any problem in osqp-eigen.

**Comment by rohitashwin** [comment] 2024-11-13 00:53
Hey traversaro thanks for the quick response. I really appreciate your help. I didn't open the issue, so you may want to consult JTylerBoylan before closing the issue.

**Comment by traversaro** [comment] 2024-11-13 00:59
I think we can close, if necessary people can post in this issue to ask to re-open or open directly a new one.

**Closed** 2024-11-13 00:59 UTC
